# docker-compose.discord.yml
# ===================================================================
# volumes & networks: Определяем их на верхнем уровне
# ===================================================================
volumes:
  redis_bot_local_data:
    driver: local

networks:
  backend_network:
    external:
      name: backend_network # 🔥 ИЗМЕНЕНИЕ: Указываем точное имя сети, созданной бэкендом

# ===================================================================
# x-templates: Используем якоря для переиспользования общих блоков
# ===================================================================
x-common-env: &common-env
  env_file: .env

x-common-restart-policy: &common-restart-policy
  restart: always

x-common-build-python: &common-build-python
  build:
    context: .
    # Dockerfile будет указан в каждом сервисе отдельно

# ===================================================================
# 🤖 СЕРВИСЫ БОТА
# ===================================================================
services:
  redis_bot_local: # Локальный Redis для бота
    image: redis:7.2-alpine
    container_name: redis_bot_local_cache
    hostname: redis_bot_local
    <<: [*common-env, *common-restart-policy] # Предполагается, что REDIS_BOT_LOCAL_PASSWORD берется из common-env
    networks: [backend_network]
    # 🔥 ИЗМЕНЕНИЕ: Добавляем --requirepass, используя REDIS_BOT_LOCAL_PASSWORD
    command: redis-server --requirepass "${REDIS_BOT_LOCAL_PASSWORD}" --appendonly yes 
    volumes:
      - redis_bot_local_data:/data
    ports: # Убедитесь, что этот порт проброшен, как мы обсуждали
      - "6380:6379" # Хост-порт:Контейнер-порт
    healthcheck:
      # 🔥 ИЗМЕНЕНИЕ: Добавляем -a "$${REDIS_BOT_LOCAL_PASSWORD}" для healthcheck
      test: ["CMD", "redis-cli", "-a", "$${REDIS_BOT_LOCAL_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  discord_bot:
    <<: [*common-env, *common-restart-policy, *common-build-python]
    networks: [backend_network]
    build:
      dockerfile: services_config/Discord_API/Dockerfile
    container_name: discord_bot_service
    command: python -u -m game_server.app_discord_bot.main # Добавляем -u для небуферизованного вывода
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDIS_LOCAL_URL=redis://redis_bot_local:6379/0
      - GAME_SERVER_API=http://fast_api:8000 # Хост fast_api из backend_network
      - CONTAINER_ID=discord_bot_service
      - GATEWAY_BOT_SECRET=${GATEWAY_BOT_SECRET}
    depends_on:
      redis_bot_local: { condition: service_healthy }
    volumes:
      - ./logs/discord_bot_output:/app/game_server/logs # Убедитесь, что Dockerfile бота копирует game_server/logs или создаёт папку