"""Обновление структуры auto_sessions

Revision ID: 05cdd9887061
Revises: d7f906cb6b68
Create Date: 2025-05-18 12:10:41.457598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05cdd9887061'
down_revision: Union[str, None] = 'd7f906cb6b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_info', 'last_login')
    op.alter_column('auto_sessions', 'next_tick_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('auto_sessions', 'last_tick_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    
    # ✅ Исправляем тип skill_key
    op.alter_column('character_skills', 'skill_key',
               existing_type=sa.String(length=100),  # Старый тип VARCHAR(100)
               type_=sa.Integer(),                   # Новый тип INTEGER
               existing_nullable=False)

    # Удаляем старые индексы
    op.drop_index('idx_character_skills_character_id', table_name='character_skills')
    op.drop_index('idx_character_skills_compound', table_name='character_skills')
    op.drop_index('idx_character_skills_skill_key', table_name='character_skills')
    op.drop_index('idx_character_skills_xp', table_name='character_skills')
    op.drop_index('idx_character_skills_xp_level', table_name='character_skills')

    # Удаляем старый внешний ключ и создаем новый
    op.drop_constraint('character_skills_skill_id_fkey', 'character_skills', type_='foreignkey')
    op.create_foreign_key(None, 'character_skills', 'characters', ['character_id'], ['character_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'character_skills', 'skills', ['skill_key'], ['skill_id'], ondelete='CASCADE')  # ✅ Обновили связь на `skill_id`

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_skills', type_='foreignkey')
    op.drop_constraint(None, 'character_skills', type_='foreignkey')
    
    # ✅ Откат изменений skill_key обратно в VARCHAR(100)
    op.alter_column('character_skills', 'skill_key',
               existing_type=sa.Integer(),        # Новый тип INTEGER
               type_=sa.String(length=100),       # Возвращаем VARCHAR(100)
               existing_nullable=False)

    op.create_foreign_key('character_skills_skill_id_fkey', 'character_skills', 'skills', ['skill_key'], ['skill_id'], ondelete='CASCADE')
    op.create_index('idx_character_skills_xp_level', 'character_skills', ['xp', 'level'], unique=False)
    op.create_index('idx_character_skills_xp', 'character_skills', ['xp'], unique=False)
    op.create_index('idx_character_skills_skill_key', 'character_skills', ['skill_key'], unique=False)
    op.create_index('idx_character_skills_compound', 'character_skills', ['character_id', 'skill_key'], unique=False)
    op.create_index('idx_character_skills_character_id', 'character_skills', ['character_id'], unique=False)

    op.alter_column('auto_sessions', 'last_tick_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('auto_sessions', 'next_tick_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('account_info', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

