"""Apply new table

Revision ID: 2476d3f45206
Revises: 09017359b072
Create Date: 2025-06-18 20:28:04.517361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2476d3f45206'
down_revision: Union[str, None] = '09017359b072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_index(op.f('ix_discord_entities_guild_id'), 'discord_entities', ['guild_id'], unique=False)
    op.create_table('used_characters_archive',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('original_pool_id', sa.Integer(), nullable=False),
    sa.Column('linked_entity_id', sa.Integer(), nullable=False),
    sa.Column('activation_type', sa.String(length=50), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=False),
    sa.Column('linked_account_id', sa.Integer(), nullable=True),
    sa.Column('simplified_pool_data', sa.JSON(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('archive_id'),
    sa.UniqueConstraint('original_pool_id')
    )
    op.create_index(op.f('ix_used_characters_archive_linked_entity_id'), 'used_characters_archive', ['linked_entity_id'], unique=False)
    op.create_unique_constraint(None, 'past_life_fragments', ['fragment_key'])
    op.create_unique_constraint(None, 'skills', ['skill_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_constraint(None, 'past_life_fragments', type_='unique')
    op.drop_index(op.f('ix_used_characters_archive_linked_entity_id'), table_name='used_characters_archive')
    op.drop_table('used_characters_archive')
    op.drop_index(op.f('ix_discord_entities_guild_id'), table_name='discord_entities')
    op.drop_table('discord_entities')
    # ### end Alembic commands ###
