"""Исправлено определение timestamp 

Revision ID: 2825c8cfade6
Revises: 05cdd9887061
Create Date: 2025-05-21 10:24:14.107017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2825c8cfade6'
down_revision: Union[str, None] = '05cdd9887061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finish_handlers',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('failed_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed_by_coordinator', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index('idx_processed_coordinator', 'finish_handlers', ['processed_by_coordinator'], unique=False)
    op.create_index('idx_status', 'finish_handlers', ['status'], unique=False)
    op.create_index('idx_task_type', 'finish_handlers', ['task_type'], unique=False)
    op.create_index('idx_timestamp', 'finish_handlers', ['timestamp'], unique=False)
    op.create_index(op.f('ix_finish_handlers_processed_by_coordinator'), 'finish_handlers', ['processed_by_coordinator'], unique=False)
    op.create_index(op.f('ix_finish_handlers_status'), 'finish_handlers', ['status'], unique=False)
    op.create_index(op.f('ix_finish_handlers_task_type'), 'finish_handlers', ['task_type'], unique=False)
    op.create_index(op.f('ix_finish_handlers_timestamp'), 'finish_handlers', ['timestamp'], unique=False)
    op.add_column('armor_templates', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('armor_templates', 'updated_at')
    op.drop_index(op.f('ix_finish_handlers_timestamp'), table_name='finish_handlers')
    op.drop_index(op.f('ix_finish_handlers_task_type'), table_name='finish_handlers')
    op.drop_index(op.f('ix_finish_handlers_status'), table_name='finish_handlers')
    op.drop_index(op.f('ix_finish_handlers_processed_by_coordinator'), table_name='finish_handlers')
    op.drop_index('idx_timestamp', table_name='finish_handlers')
    op.drop_index('idx_task_type', table_name='finish_handlers')
    op.drop_index('idx_status', table_name='finish_handlers')
    op.drop_index('idx_processed_coordinator', table_name='finish_handlers')
    op.drop_table('finish_handlers')
    # ### end Alembic commands ###
