"""Initial item generation and monster tables

Revision ID: 3003cf1d92c9
Revises: 59a91b948fd9
Create Date: 2025-06-08 11:52:34.737173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3003cf1d92c9'
down_revision: Union[str, None] = '59a91b948fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_item_code', sa.Integer(), nullable=False),
    sa.Column('suffix_code', sa.Integer(), nullable=False),
    sa.Column('accessory_name', sa.TEXT(), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('color', sa.TEXT(), nullable=False),
    sa.Column('durability', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_fragile', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('strength_percentage', sa.Double(precision=53), server_default=sa.text('0'), nullable=False),
    sa.Column('energy_pool_bonus', sa.Integer(), nullable=True),
    sa.Column('regen_energy_rate', sa.Double(precision=53), nullable=True),
    sa.Column('magic_defense_bonus', sa.Integer(), nullable=True),
    sa.Column('absorption_bonus', sa.Double(precision=53), nullable=True),
    sa.Column('reflect_damage', sa.Double(precision=53), nullable=True),
    sa.Column('damage_boost', sa.Double(precision=53), nullable=True),
    sa.Column('excluded_bonus_type', sa.TEXT(), nullable=True),
    sa.Column('effect_description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='accessory_templates_pkey')
    )
    op.create_table('armor_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_item_code', sa.Integer(), nullable=False),
    sa.Column('suffix_code', sa.Integer(), nullable=False),
    sa.Column('armor_name', sa.TEXT(), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('color', sa.TEXT(), nullable=False),
    sa.Column('physical_defense', sa.Integer(), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_fragile', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('strength_percentage', sa.Double(precision=53), server_default=sa.text('0'), nullable=False),
    sa.Column('magical_defense', sa.Integer(), nullable=True),
    sa.Column('energy_regeneration_bonus', sa.Double(precision=53), nullable=True),
    sa.Column('anti_crit', sa.Double(precision=53), nullable=True),
    sa.Column('dodge_chance', sa.Double(precision=53), nullable=True),
    sa.Column('hp_percent', sa.Double(precision=53), nullable=True),
    sa.Column('armor_boost', sa.Integer(), nullable=True),
    sa.Column('armor_percent_boost', sa.Double(precision=53), nullable=True),
    sa.Column('counter_attack', sa.Double(precision=53), nullable=True),
    sa.Column('anti_dodge', sa.Double(precision=53), nullable=True),
    sa.Column('effect_description', sa.TEXT(), nullable=True),
    sa.Column('allowed_for_class', sa.TEXT(), nullable=True),
    sa.Column('visual_asset', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='armor_templates_pkey')
    )
    op.create_table('elite_monsters',
    sa.Column('monster_instance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monster_template_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=False),
    sa.Column('last_player_killed_id', sa.Integer(), nullable=True),
    sa.Column('killed_players_count', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('killed_by_info_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unique_modifiers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('spawn_priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('monster_instance_id')
    )
    op.create_table('equipment_templates',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=False),
    sa.Column('equip_slot', sa.String(length=50), nullable=False),
    sa.Column('inventory_size', sa.String(length=10), nullable=False),
    sa.Column('material_code', sa.String(length=255), nullable=False),
    sa.Column('suffix_code', sa.String(length=255), nullable=True),
    sa.Column('base_modifiers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_tier', sa.String(length=50), nullable=True),
    sa.Column('rarity_level', sa.Integer(), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_table('instanced_items',
    sa.Column('instance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('is_equippable', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('location_slot', sa.String(length=50), nullable=True),
    sa.Column('final_modifiers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('item_category', sa.String(length=50), nullable=False),
    sa.Column('item_sub_category', sa.String(length=50), nullable=True),
    sa.Column('inventory_size', sa.String(length=10), nullable=True),
    sa.Column('current_durability', sa.Integer(), nullable=True),
    sa.Column('current_stack_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('item_base',
    sa.Column('base_item_code', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.TEXT(), nullable=False),
    sa.Column('category', sa.TEXT(), nullable=False),
    sa.Column('equip_slot', sa.TEXT(), nullable=False),
    sa.Column('base_durability', sa.Integer(), nullable=False),
    sa.Column('base_weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('base_item_code', name='item_base_pkey')
    )
    op.create_table('materials',
    sa.Column('material_code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('material_category', sa.String(length=20), nullable=False),
    sa.Column('rarity_level', sa.Integer(), nullable=True),
    sa.Column('adjective', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_fragile', sa.Boolean(), nullable=False),
    sa.Column('strength_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('material_code')
    )
    op.create_table('modifier_library',
    sa.Column('modifier_code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('effect_description', sa.TEXT(), nullable=False),
    sa.Column('value_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('randomization_range', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('modifier_code')
    )
    op.create_table('static_item_templates',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('inventory_size', sa.String(length=10), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('max_stack_size', sa.Integer(), nullable=False),
    sa.Column('base_value', sa.Integer(), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('properties_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_table('suffixes',
    sa.Column('suffix_code', sa.String(length=255), nullable=False),
    sa.Column('fragment', sa.String(length=255), nullable=False),
    sa.Column('is_for_weapon', sa.Boolean(), nullable=False),
    sa.Column('is_for_armor', sa.Boolean(), nullable=False),
    sa.Column('is_for_apparel', sa.Boolean(), nullable=False),
    sa.Column('is_for_accessory', sa.Boolean(), nullable=False),
    sa.Column('modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('suffix_code')
    )
    op.create_table('weapon_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_item_code', sa.Integer(), nullable=False),
    sa.Column('suffix_code', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.TEXT(), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('color', sa.TEXT(), nullable=False),
    sa.Column('is_fragile', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('strength_percentage', sa.Double(precision=53), server_default=sa.text('0'), nullable=False),
    sa.Column('p_atk', sa.Integer(), nullable=True),
    sa.Column('m_atk', sa.Integer(), nullable=True),
    sa.Column('crit_chance', sa.Double(precision=53), nullable=True),
    sa.Column('crit_damage_bonus', sa.Double(precision=53), nullable=True),
    sa.Column('armor_penetration', sa.Double(precision=53), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Double(precision=53), nullable=True),
    sa.Column('hp_steal_percent', sa.Double(precision=53), server_default=sa.text('0'), nullable=True),
    sa.Column('effect_description', sa.TEXT(), nullable=True),
    sa.Column('allowed_for_class', sa.TEXT(), nullable=True),
    sa.Column('visual_asset', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='weapon_templates_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon_templates')
    op.drop_table('suffixes')
    op.drop_table('static_item_templates')
    op.drop_table('modifier_library')
    op.drop_table('materials')
    op.drop_table('item_base')
    op.drop_table('instanced_items')
    op.drop_table('equipment_templates')
    op.drop_table('elite_monsters')
    op.drop_table('armor_templates')
    op.drop_table('accessory_templates')
    # ### end Alembic commands ###
