"""Accaunt game data and shard

Revision ID: 3f1ad5c9bad5
Revises: 9956cbba257c
Create Date: 2025-06-20 00:10:16.116352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1ad5c9bad5'
down_revision: Union[str, None] = '9956cbba257c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_shards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shard_name', sa.String(length=100), nullable=False),
    sa.Column('discord_guild_id', sa.BigInteger(), nullable=False),
    sa.Column('current_players', sa.Integer(), nullable=False),
    sa.Column('is_admin_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_system_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_guild_id'),
    sa.UniqueConstraint('shard_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_shards')
    # ### end Alembic commands ###
