"""New inventorygenerator

Revision ID: 4998eb79af5d
Revises: 7b21855626f7
Create Date: 2025-06-07 15:30:32.524240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4998eb79af5d'
down_revision: Union[str, None] = '7b21855626f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_rule_generator',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('quality_level', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('activation_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_inventory_rule_generator_name'), 'inventory_rule_generator', ['name'], unique=True)
    op.create_index(op.f('ix_inventory_rule_generator_quality_level'), 'inventory_rule_generator', ['quality_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_rule_generator_quality_level'), table_name='inventory_rule_generator')
    op.drop_index(op.f('ix_inventory_rule_generator_name'), table_name='inventory_rule_generator')
    op.drop_table('inventory_rule_generator')
    # ### end Alembic commands ###
