"""New CharacterPool 11111111111111

Revision ID: 59a91b948fd9
Revises: 3e28f0fe5825
Create Date: 2025-06-07 16:41:17.847158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59a91b948fd9'
down_revision: Union[str, None] = '3e28f0fe5825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_pool',
    sa.Column('character_pool_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creature_type_id', sa.Integer(), nullable=False),
    sa.Column('bloodline_id', sa.Integer(), nullable=True),
    sa.Column('personality_id', sa.Integer(), nullable=True),
    sa.Column('background_story_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('base_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visual_appearance_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('initial_skill_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('initial_role_name', sa.String(length=100), nullable=True),
    sa.Column('quality_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'available'"), nullable=False),
    sa.Column('is_unique', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rarity_score', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('death_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['background_story_id'], ['background_stories.story_id'], name='fk_cp_background_story', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bloodline_id'], ['bloodlines.bloodline_id'], name='fk_cp_bloodline', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creature_type_id'], ['creature_types.creature_type_id'], name='fk_cp_creature_type', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.personality_id'], name='fk_cp_personality', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('character_pool_id', name='character_pool_pkey')
    )
    op.create_index('idx_character_pool_creature_type', 'character_pool', ['creature_type_id'], unique=False)
    op.create_index('idx_character_pool_rarity_score', 'character_pool', ['rarity_score'], unique=False)
    op.create_index('idx_character_pool_status', 'character_pool', ['status'], unique=False)
    op.create_index(op.f('ix_character_pool_quality_level'), 'character_pool', ['quality_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_pool_quality_level'), table_name='character_pool')
    op.drop_index('idx_character_pool_status', table_name='character_pool')
    op.drop_index('idx_character_pool_rarity_score', table_name='character_pool')
    op.drop_index('idx_character_pool_creature_type', table_name='character_pool')
    op.drop_table('character_pool')
    # ### end Alembic commands ###
