"""New inventorygenerator 2

Revision ID: 5f977dac32fc
Revises: 9320bdf7a63f
Create Date: 2025-06-07 15:59:30.834373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f977dac32fc'
down_revision: Union[str, None] = '9320bdf7a63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_rule_generator_rule_key', table_name='inventory_rule_generator')
    op.create_unique_constraint(None, 'inventory_rule_generator', ['rule_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_rule_generator', type_='unique')
    op.create_index('ix_inventory_rule_generator_rule_key', 'inventory_rule_generator', ['rule_key'], unique=True)
    # ### end Alembic commands ###
