"""New inventorygenerator 5

Revision ID: 6000ffed1509
Revises: 2144ba0c15be
Create Date: 2025-06-07 16:20:36.597026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6000ffed1509'
down_revision: Union[str, None] = '2144ba0c15be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_rule_generator',
    sa.Column('rule_key', sa.String(length=150), nullable=False),
    sa.Column('rule_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('quality_level', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('activation_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('rule_key'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_index(op.f('ix_inventory_rule_generator_quality_level'), 'inventory_rule_generator', ['quality_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_rule_generator_quality_level'), table_name='inventory_rule_generator')
    op.drop_table('inventory_rule_generator')
    # ### end Alembic commands ###
