"""discord_tabl

Revision ID: 6c84f1d211e7
Revises: 0a073065d15a
Create Date: 2025-06-25 19:51:26.478491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c84f1d211e7'
down_revision: Union[str, None] = '0a073065d15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_bindings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('access_key', sa.String(), nullable=False),
    sa.Column('permissions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'access_key', name='discord_bindings_pkey')
    )
    op.drop_table('state_entities_discord')
    op.add_column('discord_entities', sa.Column('access_code', sa.String(length=50), nullable=True))
    op.add_column('discord_entities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('discord_entities_discord_id_key', 'discord_entities', type_='unique')
    op.create_index(op.f('ix_discord_entities_access_code'), 'discord_entities', ['access_code'], unique=True)
    op.create_index(op.f('ix_discord_entities_discord_id'), 'discord_entities', ['discord_id'], unique=False)
    op.create_index(op.f('ix_discord_entities_entity_type'), 'discord_entities', ['entity_type'], unique=False)
    op.create_unique_constraint('uq_guild_discord_id', 'discord_entities', ['guild_id', 'discord_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_guild_discord_id', 'discord_entities', type_='unique')
    op.drop_index(op.f('ix_discord_entities_entity_type'), table_name='discord_entities')
    op.drop_index(op.f('ix_discord_entities_discord_id'), table_name='discord_entities')
    op.drop_index(op.f('ix_discord_entities_access_code'), table_name='discord_entities')
    op.create_unique_constraint('discord_entities_discord_id_key', 'discord_entities', ['discord_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('discord_entities', 'updated_at')
    op.drop_column('discord_entities', 'access_code')
    op.create_table('state_entities_discord',
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('access_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('role_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('permissions', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['access_code'], ['state_entities.access_code'], name='fk_state_entities_discord_access_code', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'role_id', name='state_entities_discord_pkey')
    )
    op.drop_table('discord_bindings')
    # ### end Alembic commands ###
