"""New CharacterPool

Revision ID: 7b21855626f7
Revises: a55033fd5ea7
Create Date: 2025-06-07 11:07:36.991874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b21855626f7'
down_revision: Union[str, None] = 'a55033fd5ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_pool', sa.Column('initial_inventory_id', sa.Integer(), nullable=True))
    op.add_column('character_pool', sa.Column('initial_role_name', sa.String(length=100), nullable=True))
    op.drop_column('character_pool', 'initial_inventory')
    op.create_unique_constraint(None, 'discord_quest_descriptions', ['description_key'])
    op.create_unique_constraint(None, 'skills', ['skill_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_constraint(None, 'discord_quest_descriptions', type_='unique')
    op.add_column('character_pool', sa.Column('initial_inventory', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('character_pool', 'initial_role_name')
    op.drop_column('character_pool', 'initial_inventory_id')
    # ### end Alembic commands ###
