"""Apply new table

Revision ID: 7b4297c8f0e6
Revises: 2476d3f45206
Create Date: 2025-06-18 21:37:07.886840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4297c8f0e6'
down_revision: Union[str, None] = '2476d3f45206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_entities', sa.Column('permissions', sa.String(length=50), nullable=True))
    op.add_column('discord_entities', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discord_entities', 'description')
    op.drop_column('discord_entities', 'permissions')
    # ### end Alembic commands ###
