"""accaunt data pole schard

Revision ID: 807344d4145b
Revises: a0b7e25d31d8
Create Date: 2025-07-03 20:35:01.955838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '807344d4145b'
down_revision: Union[str, None] = 'a0b7e25d31d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_game_data',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('past_life_fragment_key', sa.String(length=100), nullable=True),
    sa.Column('characters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('account_cards_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shard_id', sa.BigInteger(), nullable=True),
    sa.Column('last_login_game', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_playtime_seconds', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_info.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['past_life_fragment_key'], ['past_life_fragments.fragment_key'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shard_id'], ['game_shards.discord_guild_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_game_data')
    # ### end Alembic commands ###
