"""Initial item generation and monster tables 3

Revision ID: 8e1c808ab069
Revises: ced41d3086d3
Create Date: 2025-06-08 17:45:23.507695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e1c808ab069'
down_revision: Union[str, None] = 'ced41d3086d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suffixes',
    sa.Column('suffix_code', sa.String(length=255), nullable=False),
    sa.Column('fragment', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=100), nullable=False),
    sa.Column('modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('suffix_code')
    )
    op.create_index(op.f('ix_suffixes_group'), 'suffixes', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suffixes_group'), table_name='suffixes')
    op.drop_table('suffixes')
    # ### end Alembic commands ###
