"""New inventorygenerator

Revision ID: 9320bdf7a63f
Revises: f92bbff05cd9
Create Date: 2025-06-07 15:42:59.526441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9320bdf7a63f'
down_revision: Union[str, None] = 'f92bbff05cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_rule_generator', sa.Column('rule_key', sa.String(length=150), nullable=False))
    op.drop_index('ix_inventory_rule_generator_name', table_name='inventory_rule_generator')
    op.create_index(op.f('ix_inventory_rule_generator_rule_key'), 'inventory_rule_generator', ['rule_key'], unique=True)
    op.drop_column('inventory_rule_generator', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_rule_generator', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_inventory_rule_generator_rule_key'), table_name='inventory_rule_generator')
    op.create_index('ix_inventory_rule_generator_name', 'inventory_rule_generator', ['name'], unique=True)
    op.drop_column('inventory_rule_generator', 'rule_key')
    # ### end Alembic commands ###
