"""game shard maxx_plaers

Revision ID: 93f19c6fd514
Revises: 6c84f1d211e7
Create Date: 2025-06-29 12:54:52.751535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f19c6fd514'
down_revision: Union[str, None] = '6c84f1d211e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_shards', sa.Column('max_players', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_shards', 'max_players')
    # ### end Alembic commands ###
