"""Apply new table 3

Revision ID: 9956cbba257c
Revises: 7bd7a2b24d49
Create Date: 2025-06-19 12:01:59.768490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9956cbba257c'
down_revision: Union[str, None] = '7bd7a2b24d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_bindings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('access_key', sa.String(), nullable=False),
    sa.Column('permissions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'access_key', name='discord_bindings_pkey')
    )
    op.create_table('entity_state_map',
    sa.Column('entity_access_key', sa.String(), nullable=False),
    sa.Column('access_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_access_key', 'access_code', name='entity_state_map_pkey')
    )
    op.create_table('state_entities',
    sa.Column('access_code', sa.String(length=50), nullable=False),
    sa.Column('code_name', sa.String(length=100), nullable=False),
    sa.Column('ui_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('access_code'),
    sa.UniqueConstraint('code_name')
    )
    op.create_index(op.f('ix_state_entities_access_code'), 'state_entities', ['access_code'], unique=True)
    op.create_table('state_entities_discord',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('access_code', sa.String(length=50), nullable=True),
    sa.Column('role_name', sa.TEXT(), nullable=False),
    sa.Column('permissions', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_code'], ['state_entities.access_code'], name='fk_state_entities_discord_access_code', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'role_id', name='state_entities_discord_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_entities_discord')
    op.drop_index(op.f('ix_state_entities_access_code'), table_name='state_entities')
    op.drop_table('state_entities')
    op.drop_table('entity_state_map')
    op.drop_table('discord_bindings')
    # ### end Alembic commands ###
