"""game shard maxx_plaers 2

Revision ID: a0b7e25d31d8
Revises: 93f19c6fd514
Create Date: 2025-06-30 21:50:14.586004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b7e25d31d8'
down_revision: Union[str, None] = '93f19c6fd514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_bindings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('access_key', sa.String(), nullable=False),
    sa.Column('permissions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'access_key', name='discord_bindings_pkey')
    )
    op.drop_index('ix_discord_entities_access_code', table_name='discord_entities')
    op.create_index(op.f('ix_discord_entities_access_code'), 'discord_entities', ['access_code'], unique=False)
    op.create_unique_constraint('uq_guild_access_code', 'discord_entities', ['guild_id', 'access_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_guild_access_code', 'discord_entities', type_='unique')
    op.drop_index(op.f('ix_discord_entities_access_code'), table_name='discord_entities')
    op.create_index('ix_discord_entities_access_code', 'discord_entities', ['access_code'], unique=True)
    op.drop_table('discord_bindings')
    # ### end Alembic commands ###
