"""game_location_add

Revision ID: b8f01f680b5a
Revises: 3f1ad5c9bad5
Create Date: 2025-06-21 21:39:09.045214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f01f680b5a'
down_revision: Union[str, None] = '3f1ad5c9bad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_locations',
    sa.Column('access_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('skeleton_template_id', sa.String(length=100), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('parent_access_key', sa.String(length=255), nullable=True),
    sa.Column('is_peaceful', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_access_key'], ['game_locations.access_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('access_key'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_locations')
    # ### end Alembic commands ###
