"""gamelocation updeit

Revision ID: c1c90021c655
Revises: 807344d4145b
Create Date: 2025-07-09 20:23:46.347989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c90021c655'
down_revision: Union[str, None] = '807344d4145b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_locations',
    sa.Column('access_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('skeleton_template_id', sa.String(length=100), nullable=False),
    sa.Column('specific_category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unified_display_type', sa.String(length=50), nullable=True),
    sa.Column('presentation', sa.JSON(), nullable=True),
    sa.Column('entry_point_location_id', sa.String(length=255), nullable=True),
    sa.Column('flavor_text_options', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['game_locations.access_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('access_key'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_locations')
    # ### end Alembic commands ###
