"""Add or update GameLocation table

Revision ID: ce9eada5b63f
Revises: 
Create Date: 2025-07-26 21:55:52.760436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce9eada5b63f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_locations',
    sa.Column('access_key', sa.String(length=255), nullable=False, comment="Иерархический ID 'X-XX-YY-ZZZ'. Главный ключ для связей."),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный внутренний ID записи в базе.'),
    sa.Column('parent_id', sa.String(length=255), nullable=True, comment='access_key родительской локации для иерархии.'),
    sa.Column('specific_category', sa.String(length=50), nullable=False, comment='Внутренний тип для логики: QUARTER, HUB_LOCATION, POI, INTERIOR, GATEWAY.'),
    sa.Column('unified_display_type', sa.String(length=50), nullable=True, comment='Внешний тип для отображения (для ботов и т.д.): Город, Магазин.'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Теги для логики: ["безопасная_зона", "торговля"].'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Отображаемое название локации.'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='Основной описательный текст для панорамы.'),
    sa.Column('presentation', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Данные для панорамы: {"image_url": "...", "sound_key": "..."}.'),
    sa.Column('flavor_text_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Список случайных фраз для разнообразия.'),
    sa.Column('exits', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Список выходов: [{"label": "Войти", "target": "1-50-01-001"}].'),
    sa.Column('entry_point_location_id', sa.String(length=255), nullable=True, comment='Для QUARTER: access_key точки входа в квартал.'),
    sa.Column('skeleton_template_id', sa.String(length=100), nullable=True, comment='ID шаблона для процедурной генерации (если используется).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['game_locations.access_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('access_key'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_locations')
    # ### end Alembic commands ###
