"""Initial item generation and monster tables 2

Revision ID: ced41d3086d3
Revises: 3003cf1d92c9
Create Date: 2025-06-08 16:32:20.587174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ced41d3086d3'
down_revision: Union[str, None] = '3003cf1d92c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_base', sa.Column('properties_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('item_base', 'base_item_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('item_base', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('item_base', 'item_name')
    op.drop_column('item_base', 'equip_slot')
    op.drop_column('item_base', 'base_weight')
    op.drop_column('item_base', 'base_durability')
    op.alter_column('suffixes', 'group',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.drop_column('suffixes', 'is_for_accessory')
    op.drop_column('suffixes', 'is_for_armor')
    op.drop_column('suffixes', 'is_for_apparel')
    op.drop_column('suffixes', 'is_for_weapon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suffixes', sa.Column('is_for_weapon', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('suffixes', sa.Column('is_for_apparel', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('suffixes', sa.Column('is_for_armor', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('suffixes', sa.Column('is_for_accessory', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('suffixes', 'group',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'SYSTEM'::character varying"),
               existing_nullable=False)
    op.add_column('item_base', sa.Column('base_durability', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item_base', sa.Column('base_weight', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item_base', sa.Column('equip_slot', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('item_base', sa.Column('item_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('item_base', 'category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('item_base', 'base_item_code',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('item_base', 'properties_json')
    # ### end Alembic commands ###
