CREATE TABLE IF NOT EXISTS armor_templates (
    id integer NOT NULL,
    base_item_code integer NOT NULL,
    suffix_code integer NOT NULL,
    name text NOT NULL,
    rarity integer NOT NULL,
    color text NOT NULL,
    physical_defense integer NOT NULL,
    magical_defense integer,
    durability integer NOT NULL,
    weight integer NOT NULL,
    energy_regeneration_bonus double precision,
    anti_crit double precision,
    dodge_chance double precision,
    hp_percent double precision,
    armor_boost integer,
    armor_percent_boost double precision,
    counter_attack double precision,
    anti_dodge double precision,
    effect_description text,
    allowed_for_class text,
    visual_asset text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_fragile boolean DEFAULT false NOT NULL,
    strength_percentage double precision DEFAULT 0 NOT NULL
)
