CREATE TABLE public.character_status (
    player_id integer NOT NULL,
    current_health integer,
    max_health integer,
    experience integer,
    level integer,
    current_energy integer,
    crit_chance double precision,
    crit_damage_bonus double precision,
    anti_crit_chance double precision,
    anti_crit_damage double precision,
    dodge_chance double precision,
    anti_dodge_chance double precision,
    counter_attack_chance double precision,
    parry_chance double precision,
    block_chance double precision,
    armor_penetration double precision,
    physical_attack double precision,
    magical_attack double precision,
    magic_resistance double precision,
    physical_resistance double precision,
    mana_cost_reduction double precision,
    regen_health_rate double precision,
    energy_regeneration_bonus double precision,
    energy_pool_bonus integer,
    absorption_bonus double precision,
    shield_value double precision,
    shield_regeneration double precision,
    gear_score integer,
    luck double precision,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "IE" integer
)
