INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (208, 'Наручи', 'armor', 'руки', 35, 35);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (209, 'Рукава', 'armor', 'руки', 10, 10);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (210, 'Сапоги', 'armor', 'ноги', 25, 25);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (211, 'Ботинки', 'armor', 'ноги', 20, 20);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (212, 'латные сапоги', 'armor', 'ноги', 40, 40);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (101, 'дубина', 'weapon', 'hand', 50, 2);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (102, 'двуручный посох', 'weapon', 'hand', 50, 2);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (103, 'сабля', 'weapon', 'hand', 40, 2);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (104, 'меч', 'weapon', 'hand', 40, 2);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (105, 'секира', 'weapon', 'hand', 60, 2);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (106, 'двуручный меч', 'weapon', 'hand', 60, 2);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (107, 'двуручный топор', 'weapon', 'hand', 60, 2);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (108, 'кинжал', 'weapon', 'hand', 25, 1);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (109, 'копье', 'weapon', 'hand', 25, 1);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (110, 'длинный лук', 'weapon', 'hand', 30, 1);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (111, 'короткий лук', 'weapon', 'hand', 30, 1);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (301, 'Кольцо', 'accessory', 'ring', 0, 2);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (302, 'Серьги', 'accessory', 'ear', 0, 3);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (303, 'Ожерелье', 'accessory', 'neck', 0, 5);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (304, 'Щит', 'accessory', 'hand', 0, 0);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (305, 'Символ', 'accessory', 'hand', 0, 0);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (306, 'Плащ', 'accessory', 'back', 0, 0);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (201, 'Доспех', 'armor', 'туловище', 50, 50);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (202, 'Кираса', 'armor', 'туловище', 30, 30);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (203, 'Роба', 'armor', 'туловище', 15, 15);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (204, 'Шлем', 'armor', 'голова', 25, 25);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (205, 'Капюшон', 'armor', 'голова', 15, 15);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (206, 'латные сапоги', 'armor', 'голова', 40, 40);
INSERT INTO item_base (base_item_code, item_name, category, equip_slot, base_durability, base_weight) VALUES (207, 'Перчатки', 'armor', 'руки', 20, 20);
