INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (20, 20, 'piercing_resistance', 'Сопротивление колющему урону');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (21, 21, 'slashing_resistance', 'Сопротивление рубящему урону');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (22, 22, 'blunt_resistance', 'Сопротивление дробящему урону');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (23, 39, 'armor_flat_bonus', 'Базовый бонус к броне');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (24, 23, 'mana_cost_reduction', 'Снижение расхода маны');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (25, 24, 'regen_health_rate', 'Восстановление здоровья');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (26, 25, 'energy_regeneration_bonus', 'Регенерация энергии');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (27, 35, 'energy_pool_bonus', 'Бонус к пулу энергии');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (28, 26, 'fire_power_bonus', 'Усиление магии Огня');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (29, 27, 'water_power_bonus', 'Усиление магии Воды');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (30, 28, 'air_power_bonus', 'Усиление магии Воздуха');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (31, 29, 'earth_power_bonus', 'Усиление магии Земли');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (32, 30, 'light_power_bonus', 'Усиление магии Света');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (33, 31, 'dark_power_bonus', 'Усиление магии Тьмы');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (34, 32, 'gold_bonus_percent', 'Бонус к получаемому золоту');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (35, 33, 'drop_chance_boost', 'Увеличение шанса выпадения предметов');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (1, 1, 'crit_chance', 'Шанс критического удара');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (2, 2, 'crit_damage_bonus', 'Усиление критического урона');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (3, 3, 'anti_crit_chance', 'Сопротивление критам');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (4, 4, 'anti_crit_damage', 'Ослабление критического урона');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (5, 5, 'dodge_chance', 'Шанс увертывания');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (6, 6, 'anti_dodge_chance', 'Против увертывания');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (7, 7, 'counter_attack_chance', 'Шанс контрудара');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (8, 8, 'parry_chance', 'Шанс парирования');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (9, 9, 'block_chance', 'Шанс блока щитом');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (10, 10, 'armor_penetration', 'Удар сквозь броню');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (11, 11, 'physical_attack', 'Физическая атака');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (12, 12, 'magical_attack', 'Магическая атака');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (13, 13, 'damage_boost', 'Усиление общего урона');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (14, 14, 'piercing_damage_bonus', 'Усиление колющего урона');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (15, 15, 'slashing_damage_bonus', 'Усиление рубящего урона');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (16, 16, 'blunt_damage_bonus', 'Усиление дробящего урона');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (17, 17, 'armor_boost', 'Увеличение брони');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (18, 18, 'magic_resistance', 'Сопротивление магии');
INSERT INTO modifiers_library (id, access_modifier, modifier_name, effect_description) VALUES (19, 19, 'physical_resistance', 'Сопротивление физическому урону');
